# Generated by Django 5.2.6 on 2025-09-16 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Esta migración se ha convertido en NO-OP para evitar duplicados de columnas.
    # Los campos ya se crean correctamente en 0001_initial.
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = []
