# Generated by Django 5.2.7 on 2025-10-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # NO-OP: Los cambios ya están aplicados en 0001_initial.
    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = []
