# Generated by Django 5.2.6 on 2025-12-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_estado_rename_telefono_pedido_telefono_contacto_and_more'),
        ('products', '0006_combopersonalizadoproducto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='producto_personalizado',
            field=models.ForeignKey(blank=True, help_text='Producto personalizado publicado agregado al carrito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='products.productopersonalizado'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto_personalizado',
            field=models.ForeignKey(blank=True, help_text='Producto personalizado publicado que fue comprado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_realizados', to='products.productopersonalizado'),
        ),
    ]
