# Generated by Django 5.2.6 on 2025-12-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_carritoitem_producto_personalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='puntos_asignados',
            field=models.BooleanField(default=False, help_text='Indica si ya se asignaron los puntos por este pedido'),
        ),
    ]
