# Generated by Django 5.2.9 on 2025-12-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_publicado_veces_comprado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combopersonalizado',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='combopersonalizadoproducto',
            name='imagen_seleccionada',
            field=models.CharField(blank=True, help_text='Ruta de la imagen específica seleccionada en el personalizador', max_length=200, null=True),
        ),
    ]
