# Generated by Django 5.2.6 on 2025-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_combopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combopersonalizadoproducto',
            name='precio_al_agregar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del producto al momento de agregarlo al combo', max_digits=8, null=True),
        ),
    ]