# Generated by Django 5.2.6 on 2025-12-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_combopersonalizadoproducto_precio_al_agregar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combopersonalizadoproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del producto al momento de agregarlo al combo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='combopersonalizadoproducto',
            name='precio_al_agregar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del producto al momento de agregarlo al combo', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personalizado', models.CharField(help_text='Nombre dado por el usuario al producto personalizado', max_length=200)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False, help_text='Si está publicado, otros usuarios pueden comprarlo')),
                ('veces_comprado', models.PositiveIntegerField(default=0, help_text='Cantidad de veces que otros han comprado este producto')),
                ('is_paid', models.BooleanField(default=False, help_text='Indica si el producto ha sido pagado por su creador')),
                ('stripe_session_id', models.CharField(blank=True, help_text='ID de la sesión de Stripe usada para pagar este producto', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se registró el pago exitoso', null=True)),
                ('producto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='products.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPersonalizadoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingrediente')),
                ('producto_personalizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productopersonalizado')),
            ],
        ),
        migrations.AddField(
            model_name='productopersonalizado',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos_personalizados', through='products.ProductoPersonalizadoIngrediente', to='products.ingrediente'),
        ),
    ]
