# Generated by Django 5.2.6 on 2025-12-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_combopersonalizadoproducto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopersonalizado',
            name='local_product_id',
            field=models.CharField(blank=True, help_text='ID del producto local (ej: hamburguesa1)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productopersonalizado',
            name='local_product_image',
            field=models.CharField(blank=True, help_text='Path de la imagen del producto local', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productopersonalizado',
            name='local_product_name',
            field=models.CharField(blank=True, help_text='Nombre del producto base local', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productopersonalizado',
            name='producto_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='products.producto'),
        ),
    ]
