# Generated by Django 5.2.6 on 2025-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_purchasehistory_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='original_product_id',
            field=models.CharField(blank=True, help_text='ID del producto base original', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='original_product_image',
            field=models.CharField(blank=True, help_text='URL/path de la imagen del producto original', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='original_product_name',
            field=models.CharField(blank=True, help_text='Nombre del producto base original', max_length=200, null=True),
        ),
    ]
