# Generated by Django 5.2.6 on 2025-12-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_purchaseitem_original_product_id_and_more'),
    ]

    operations = [
    ]
